name: Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # ou autre version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet publish ./LocaCraft/LocaCraft.csproj -c Release -o ./publish

      - name: Archive published files
        uses: actions/upload-artifact@v4
        with:
          name: LocaCraft
          path: ./publish
